### ISSUE TITLE
Latest Docker image doesn't recognize the "rymtl" command

### ISSUE THREAD

**Issue by basavesh** [doganulus/reelay#10]
Can't run examples directly in docker image. Is there some setup involved like setting up the path or compiling the source code inside the docker?

> root@da712a2de8c3:/home/reelay# rymtl '{p1} since[18:24] {p2}' reelay/apps/mtl/examples/2.csv --verbose 1
bash: rymtl: command not found

**Comment by doganulus** [comment]
Docker documentation is updated:
https://doganulus.github.io/reelay/docker/
