### ISSUE TITLE
can't find "reelay/recipes.hpp"

### ISSUE THREAD

**Issue by basavesh** [doganulus/reelay#11]
I am trying to follow the tutorials and could not find the file "reelay/recipes.hpp".

**Comment by doganulus** [comment]
The documentation and tutorial for C++ is not up-to-date. Once I revamp the C++ API, they will be updated.

For now I suggest using Python and looking at example at https://github.com/doganulus/reelay/tree/master/python/tests

**Comment by doganulus** [comment]
Now tutorial documentation is up-to-date with the codebase.

Docs: https://doganulus.github.io/reelay/
