### ISSUE TITLE
std::bad cast in python binding when using nested structure

### ISSUE THREAD

**Issue by jcarrano** [doganulus/reelay#17]
# Description

After updating from version 2005 to 2008 I cannot use nested structures (e.g. `A:{B}`) any more.

I would like to solve it myself, but unfortunately I don't have any experience with pybind11.

# Steps to reproduce:

```
Python 3.8.5 (default, Jul 27 2020, 08:42:51) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from reelay import dense_timed_monitor
>>> my_monitor = dense_timed_monitor( pattern="A::{B}", semantics="boolean", piecewise='constant')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jcarrano/source/mtl-tests/env/lib/python3.8/site-packages/reelay/dense_timed_monitor.py", line 29, in __new__
    return reelay.library.dense_monitor.make(pattern, options)
RuntimeError: std::bad_cast
```

**Comment by doganulus** [comment]
Yes, I have removed nested structures in v2008 as they were half-baked. Currently monitors work on flat json/dict objects.

I would love to hear about your particular use case. Could you elaborate the case and the structure of json/python objects that you would like to monitor? 

Thanks.

**Comment by jcarrano** [comment]
Dogan, first of all, thanks for making public this software. I stated using it only a short time ago.

I am monitoring MQTT messages which are composed of JSON objects. Convert MQTT topics into objects (e.g. "a/b/c" goes to {"a": {"b": {"c":{}}}) and put the payload object into the innermost sub-objects.

On a second thought, I could ditch this (admittedly complicated) logic and flatten all using name mangling (e.g. "a__b__c__etc"). In fact (correct me if I'm wrong), all of v2005's nested structured features can be emulated using flat, mangled names, since Rye-2005 only allowed operating on leaf values.

**Comment by doganulus** [comment]
Yes, the workaround is flattennig the JSON objects. Two popular choices are using dots ("a.b.c") as in Javascript or using slashes ("/a/b/c") as in JSON pointer standard. 

The other alternative is to use a python type that supports nested keys. Below is an example code that uses `pyhocon` library.

```python
from reelay import discrete_timed_monitor
from pyhocon import ConfigFactory

my_monitor = discrete_timed_monitor(
    pattern=r"{'root.speed' > 13.0} since[:3] {'root.lights_on'}",  #notice the quotes on nested keys
    condense=False
)

input_sequence = [
    dict(root=dict(speed=3.3,  lights_on=False)),
    dict(root=dict(speed=6.3,  lights_on=False)),
    dict(root=dict(speed=9.3,  lights_on=True)),
    dict(root=dict(speed=13.3, lights_on=False)),
    dict(root=dict(speed=13.4, lights_on=False)),
    dict(root=dict(speed=13.3, lights_on=False)),
    dict(root=dict(speed=13.2, lights_on=False)),
    dict(root=dict(speed=13.2, lights_on=False)),
]

result = []
for x in input_sequence:
    y = my_monitor.update(ConfigFactory.from_dict(x))  #converting to hocon type
    result.append(y)

expected = [
    {'value': False},
    {'value': False},
    {'value': True},
    {'value': True},
    {'value': True},
    {'value': True},
    {'value': False},
    {'value': False}]

print(result == expected)
```
This works because Reelay takes the string in the specification, and use it directly to access object fields.
