### ISSUE TITLE
Segmentation fault while making monitor with References and Quantifiers

### ISSUE THREAD

**Issue by clementber** [doganulus/reelay#21]
The methode reelay::make_monitor generate segmentation fault when the formula contains a quantifier operator. For example, based on the example given in "apps\tutorial\door_open_warning\cpp\dense_tutorial_main.cpp" and the formula from rye.md

```
#include <string>
#include <vector>
#include <fstream>
#include <iostream>

#include "reelay/monitors.hpp"

int main(int argc, const char *argv[]) {

  using time_type = double;
  using input_type = reelay::json;
  using output_type = reelay::json;

  if (argc != 2) {
    std::cout << "Error: Program requires a filename argument." << std::endl;
    return -1;
  }

  std::ifstream input_file(argv[1]);

  // Monitor constructions
  auto options = reelay::dense_timed<time_t>::monitor<
      input_type, output_type>::options();

  std::cout << "Before make_monitor.\n";
  auto my_monitor_2 = reelay::make_monitor(
      "exists[refname]. {key1: *refname, key2: *refname}", options);

  std::cout << "After make monitor\n";
  return 0;
}
```

The output is :

```
# g++ -o tests tests.cpp -lcudd
# ./test examples/test.jsonl
Before make_monitor.
Segmentation fault (core dumped)
```

The same issues is happening with ryjson1 when I run it as follow : 

```
# ./bin/ryjson1 'exists[refname]. {key1: *refname, key2: *refname}' ./test.jsonl
Segmentation fault (core dumped)
```

**Comment by doganulus** [comment]
The parser needs `-pthread` option when linking on some platforms including Ubuntu.

Otherwise unittests are working for me. Could you run them with `make test` and report the outcome in any case?

**Comment by clementber** [comment]
I run the unittests and they works fine. So I got through them and looked at the one about the quantifiers operators and it seems a `data_manager` need to be set in the monitor's options to be able to parse the formula. I don't think it's told in the documentation, but I might have missed it... ^^'

The code of my first message can be fixed by adding : 

```
  auto manager = std::make_shared<reelay::binding_manager>();
  auto options = reelay::dense_timed<time_t>::monitor<
      input_type, output_type>::options().with_data_manager(manager);
```

I haven't check if the generated monitor run fine yet. But, I would advise to check in the methods `make_monitor` of monitor.hpp if there is a `data_manager` set in `opt` when references are detected. If not, then print an error message advising to set it with the method `with_data_manager()`. This might help other people that forgot to set it to understand what is happening.

To solve it in ryjson1, a simple (naive?) way might simply be to always set a `data_manager` in the option of the monitor. However, I guess that it might have drawback on the performances when it's not needed. If so, maybe add a flag option to trigger it when needed or detect in the formula if a `data_manager` is needed with a first parsing step.

Sorry to have bother you with this, and thanks for your quick answer :-)

**Comment by clementber** [comment]
After further tests, the monitor seems to work correctly. I noticed that the method `update` of monitor using a quantifier operator return `null` instead of `[ ]` when the truth value remain the same. It should maybe be unified to avoid unexpected errors.
